In [214]:
import pandas as pd
import numpy as np

In [215]:
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score,confusion_matrix

from sklearn.metrics import precision_score,recall_score

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [216]:
df = pd.read_csv('Iris_data.csv')

In [217]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [218]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [220]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [221]:
encoder = LabelEncoder()

In [222]:
df['Species'] = encoder.fit_transform(df['Species'])

In [223]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [224]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [225]:
model = LogisticRegression()

In [226]:
model2 = DecisionTreeClassifier()

In [227]:
model.fit(x_train, y_train)

C:\Users\shoab\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [228]:
model2.fit(x_train, y_train)

DecisionTreeClassifier()

In [229]:
prediction = model.predict(x_test)

In [230]:
prediction2 = model2.predict(x_test)

In [231]:
accuracy_score(y_test, prediction)

1.0

In [232]:
accuracy_score(y_test, prediction2)

0.9666666666666667

In [233]:
confusion_matrix(y_test, prediction2)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [234]:
confusion_matrix(y_test, prediction)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)

In [235]:
merge = pd.DataFrame()

In [236]:
merge['actual_value'] = y_test

In [237]:
merge['prediction_value1'] = prediction

In [238]:
merge['prediction_value2'] = prediction2

In [239]:
merge

actual_value  prediction_value1  prediction_value2
14              0                  0                  0
98              1                  1                  1
75              1                  1                  1
16              0                  0                  0
131             2                  2                  2
56              1                  1                  1
141             2                  2                  2
44              0                  0                  0
29              0                  0                  0
120             2                  2                  2
94              1                  1                  1
5               0                  0                  0
102             2                  2                  2
51              1                  1                  1
78              1                  1                  1
42              0                  0                  0
92              1                  1                  1
66              1                  1                  1
31              0                  0                  0
35              0                  0                  0
90              1                  1                  1
84              1                  1                  1
77              1                  1                  1
40              0                  0                  0
125             2                  2                  2
99              1                  1                  2
33              0                  0                  0
19              0                  0                  0
73              1                  1                  1
146             2                  2                  2

In [240]:
precision_score(y_test, prediction, average=None)

array([1., 1., 1.])

In [241]:
precision_score(y_test, prediction2, average=None)

array([1.        , 1.        , 0.85714286])

In [242]:
recall_score(y_test, prediction2, average=None)

array([1.        , 0.92307692, 1.        ])

In [243]:
recall_score(y_test, prediction, average=None)

array([1., 1., 1.])