In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('digit_train.csv')

In [3]:
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier


from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score,confusion_matrix

from sklearn.metrics import precision_score,recall_score,f1_score

from sklearn.metrics import classification_report

In [5]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [6]:
x_train

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
21250       0       0       0       0       0       0       0       0       0   
20334       0       0       0       0       0       0       0       0       0   
29647       0       0       0       0       0       0       0       0       0   
3220        0       0       0       0       0       0       0       0       0   
5293        0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
31019       0       0       0       0       0       0       0       0       0   
30280       0       0       0       0       0       0       0       0       0   
6637        0       0       0       0       0       0       0       0       0   
35343       0       0       0       0       0       0       0       0       0   
23720       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
21250       0  ...         0         0         0         0         0   
20334       0  ...         0         0         0         0         0   
29647       0  ...         0         0         0         0         0   
3220        0  ...         0         0         0         0         0   
5293        0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
31019       0  ...         0         0         0         0         0   
30280       0  ...         0         0         0         0         0   
6637        0  ...         0         0         0         0         0   
35343       0  ...         0         0         0         0         0   
23720       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
21250         0         0         0         0         0  
20334         0         0         0         0         0  
29647         0         0         0         0         0  
3220          0         0         0         0         0  
5293          0         0         0         0         0  
...         ...       ...       ...       ...       ...  
31019         0         0         0         0         0  
30280         0         0         0         0         0  
6637          0         0         0         0         0  
35343         0         0         0         0         0  
23720         0         0         0         0         0  

[33600 rows x 784 columns]

In [7]:
x_test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
38732       0       0       0       0       0       0       0       0       0   
3686        0       0       0       0       0       0       0       0       0   
30090       0       0       0       0       0       0       0       0       0   
31205       0       0       0       0       0       0       0       0       0   
11331       0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
22794       0       0       0       0       0       0       0       0       0   
2447        0       0       0       0       0       0       0       0       0   
10794       0       0       0       0       0       0       0       0       0   
5497        0       0       0       0       0       0       0       0       0   
16988       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
38732       0  ...         0         0         0         0         0   
3686        0  ...         0         0         0         0         0   
30090       0  ...         0         0         0         0         0   
31205       0  ...         0         0         0         0         0   
11331       0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
22794       0  ...         0         0         0         0         0   
2447        0  ...         0         0         0         0         0   
10794       0  ...         0         0         0         0         0   
5497        0  ...         0         0         0         0         0   
16988       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
38732         0         0         0         0         0  
3686          0         0         0         0         0  
30090         0         0         0         0         0  
31205         0         0         0         0         0  
11331         0         0         0         0         0  
...         ...       ...       ...       ...       ...  
22794         0         0         0         0         0  
2447          0         0         0         0         0  
10794         0         0         0         0         0  
5497          0         0         0         0         0  
16988         0         0         0         0         0  

[8400 rows x 784 columns]

In [8]:
y_train

21250    2
20334    3
29647    2
3220     9
5293     0
        ..
31019    7
30280    9
6637     2
35343    9
23720    4
Name: label, Length: 33600, dtype: int64

In [9]:
y_test

38732    6
3686     9
30090    5
31205    7
11331    9
        ..
22794    7
2447     3
10794    3
5497     6
16988    9
Name: label, Length: 8400, dtype: int64

In [10]:
model = LogisticRegression()

In [11]:
model2 = DecisionTreeClassifier()

In [13]:
model.fit(x_train, y_train)

C:\Users\shoab\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
model2.fit(x_train, y_train)

DecisionTreeClassifier()

In [15]:
prediction = model.predict(x_test)

In [16]:
prediction2 = model2.predict(x_test)

In [17]:
accuracy_score(y_test, prediction)

0.9145238095238095

In [18]:
accuracy_score(y_test, prediction2)

0.8527380952380952

In [20]:
confusion_matrix(y_test, prediction)

array([[791,   0,   1,   0,   1,   9,  11,   1,   6,   1],
       [  0, 938,   2,   4,   0,   3,   0,   3,  12,   0],
       [  2,   9, 745,  16,   9,   4,  13,  13,  15,   3],
       [  1,   4,  19, 763,   0,  36,   5,   5,  20,  11],
       [  2,   5,   4,   0, 804,   1,   7,   3,   9,  21],
       [  9,   3,   4,  23,  10, 610,  15,  10,  34,  11],
       [ 12,   4,  12,   1,   7,   8, 789,   0,   5,   1],
       [  3,   2,  13,   6,   4,   2,   0, 812,   2,  29],
       [ 11,  12,  13,  18,   1,  21,   6,   6, 694,  11],
       [  3,   6,   2,  14,  25,   4,   0,  37,   7, 736]], dtype=int64)

In [21]:
confusion_matrix(y_test, prediction2)

array([[755,   2,  13,   2,   5,  18,   9,   3,   9,   5],
       [  0, 900,  11,  10,   7,   4,   4,  10,  13,   3],
       [ 12,  25, 657,  37,  19,  13,  17,  21,  19,   9],
       [  4,  12,  26, 697,   9,  49,   6,  14,  31,  16],
       [  5,   5,   7,   9, 734,  12,   9,  11,  17,  47],
       [ 10,   7,  14,  44,   8, 580,  16,  12,  25,  13],
       [  9,   1,  11,   6,  19,  22, 753,   0,  13,   5],
       [  4,   9,  23,  12,   6,   4,   1, 780,   9,  25],
       [ 14,   8,  22,  37,  17,  29,  16,   6, 624,  20],
       [  8,   4,  10,  18,  42,  16,   4,  24,  25, 683]], dtype=int64)

In [23]:
precision_score(y_test, prediction, average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [24]:
precision_score(y_test, prediction, average='weighted')

0.9142150713630827

In [25]:
precision_score(y_test, prediction2, average='weighted')

0.8526712694313519

In [27]:
recall_score(y_test, prediction, average='weighted')

0.9145238095238095

In [28]:
recall_score(y_test, prediction2, average='weighted')

0.8527380952380952

In [30]:
f1_score(y_test, prediction, average='weighted')

0.9142794994052751

In [31]:
f1_score(y_test, prediction2, average='weighted')

0.8526429827409038

In [37]:
report_dict = classification_report(y_test, prediction, output_dict=True)

In [38]:
df2 = pd.DataFrame(report_dict).transpose()

In [39]:
df2

precision    recall  f1-score      support
0              0.948441  0.963459  0.955891   821.000000
1              0.954222  0.975052  0.964524   962.000000
2              0.914110  0.898673  0.906326   829.000000
3              0.902959  0.883102  0.892920   864.000000
4              0.933798  0.939252  0.936517   856.000000
5              0.873926  0.836763  0.854940   729.000000
6              0.932624  0.940405  0.936499   839.000000
7              0.912360  0.930126  0.921157   873.000000
8              0.863184  0.875158  0.869130   793.000000
9              0.893204  0.882494  0.887817   834.000000
accuracy       0.914524  0.914524  0.914524     0.914524
macro avg      0.912883  0.912448  0.912572  8400.000000
weighted avg   0.914215  0.914524  0.914279  8400.000000