In [419]:
import pandas as pd
import numpy as np

In [420]:
from sklearn.model_selection import train_test_split


from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score


from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDRegressor

In [421]:
x,y = load_diabetes(return_X_y=True)

In [422]:

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [423]:
model = SGDRegressor(penalty='l2',max_iter=500,eta0=0.1,learning_rate='constant',alpha=0.001)

In [424]:
model.fit(x,y)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [425]:
prediction = model.predict(x_test)

In [426]:
r2_score(y_test, prediction)

0.42670629322133247

In [427]:
model.coef_

array([  23.57224475, -131.8544062 ,  388.87041114,  252.73980311,
        -16.23106192,  -65.23636169, -177.51917252,  121.82785923,
        331.24230367,  112.30616747])

In [428]:
model.intercept_

array([139.33451444])

In [429]:
model2 = Ridge(alpha=0.001, max_iter=500,solver='sparse_cg')

In [430]:
model2.fit(x_train, y_train)

Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [431]:
prediction2 = model2.predict(x_test)

In [432]:
r2_score(y_test, prediction2)

0.4534280296653138

In [433]:
model2.coef_

array([  38.48350782, -241.35179305,  543.83518292,  346.78283412,
       -827.70198998,  437.17375331,  116.94974928,  260.75926999,
        696.12922851,   49.74345128])

In [434]:
model2.intercept_

151.3419805391815

In [435]:
class grad_descent_ridge:
    
    def __init__(self,epochs,learning_rate,alpha):
        
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,x_train,y_train):
        
        self.coef_ = np.ones(x_train.shape[1])
        self.intercept_ = 0
        thetha = np.insert(self.coef_,0,self.intercept_)
        
        x_train = np.insert(x_train,0,1,axis=1)
        
        for i in range(self.epochs):
            thetha_der = np.dot(x_train.T,x_train).dot(thetha) - np.dot(x_train.T,y_train) + self.alpha*thetha
            thetha = thetha - self.learning_rate*thetha_der
        
        self.coef_ = thetha[1:]
        self.intercept_ = thetha[0]
    
    def predict(self,x_test):
        
        return np.dot(x_test,self.coef_) + self.intercept_

In [436]:
model3 = grad_descent_ridge(epochs=500,alpha=0.001,learning_rate=0.005)

In [437]:
model3.fit(x_train, y_train)

In [438]:
model3.coef_

array([  43.37183861, -192.03766574,  496.43542567,  319.37407   ,
        -64.42788084, -113.194338  , -213.9073644 ,  144.86136322,
        367.67948022,  119.56857869])

In [439]:
model3.intercept_

151.4045475591972

In [440]:
r2_score(y_test, model3.predict(x_test))

0.4592249376936409