In [2]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [3]:
digit = load_digits()

In [4]:
digit

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [7]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x = digit.data
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [10]:
y = digit.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=0.2)

In [12]:
len(x_train)

1437

In [13]:
len(y_test)

360

In [14]:
lr = LogisticRegression(max_iter=2000)

In [15]:
lr.fit(x_train, y_train)

LogisticRegression(max_iter=2000)

In [16]:
lr.predict(x_test)

array([9, 2, 5, 9, 2, 1, 5, 8, 1, 0, 5, 3, 5, 9, 7, 1, 2, 1, 8, 2, 3, 3,
       5, 1, 9, 6, 2, 7, 5, 2, 0, 1, 2, 7, 6, 7, 5, 7, 5, 4, 4, 7, 4, 6,
       9, 8, 5, 6, 8, 4, 9, 5, 5, 2, 7, 9, 8, 6, 8, 0, 9, 0, 1, 3, 6, 6,
       4, 2, 8, 6, 0, 2, 9, 1, 2, 3, 5, 6, 6, 2, 5, 1, 1, 7, 8, 3, 6, 8,
       8, 8, 7, 7, 8, 4, 7, 6, 0, 7, 3, 7, 9, 5, 0, 3, 4, 1, 7, 7, 8, 1,
       7, 6, 4, 2, 3, 4, 0, 5, 1, 6, 5, 9, 3, 5, 3, 6, 1, 9, 9, 9, 5, 7,
       1, 7, 7, 7, 4, 5, 1, 7, 1, 7, 8, 9, 6, 7, 0, 5, 6, 1, 6, 5, 2, 8,
       4, 8, 7, 5, 4, 0, 6, 6, 1, 3, 5, 1, 2, 1, 3, 8, 8, 1, 8, 2, 3, 6,
       9, 3, 0, 4, 6, 5, 1, 7, 2, 6, 6, 7, 9, 6, 1, 9, 2, 4, 4, 4, 8, 1,
       4, 6, 0, 3, 3, 3, 5, 4, 5, 9, 6, 1, 3, 2, 0, 1, 5, 3, 1, 1, 3, 0,
       2, 2, 6, 8, 5, 4, 9, 7, 3, 2, 8, 0, 8, 2, 1, 9, 9, 4, 0, 4, 6, 7,
       9, 1, 4, 1, 1, 7, 4, 4, 5, 3, 1, 7, 7, 9, 6, 5, 0, 2, 2, 6, 8, 9,
       2, 1, 8, 3, 1, 9, 3, 4, 7, 4, 8, 1, 7, 7, 0, 3, 6, 8, 9, 0, 4, 4,
       4, 5, 2, 3, 4, 9, 4, 9, 1, 0, 5, 1, 6, 9, 9,

In [17]:
lr.score(x_test, y_test)

0.9666666666666667

In [18]:
svm = SVC()

In [19]:
svm.fit(x_train, y_train)

SVC()

In [20]:
svm.predict(x_test)

array([9, 2, 5, 9, 2, 1, 5, 8, 1, 0, 5, 3, 5, 9, 7, 1, 2, 1, 8, 2, 3, 3,
       5, 1, 9, 6, 2, 7, 5, 2, 0, 1, 2, 7, 6, 7, 5, 7, 5, 4, 4, 7, 4, 6,
       9, 8, 5, 6, 8, 4, 9, 5, 5, 2, 7, 9, 8, 6, 8, 0, 9, 0, 1, 3, 6, 6,
       4, 2, 8, 6, 0, 2, 9, 1, 2, 3, 5, 6, 6, 2, 5, 1, 8, 7, 8, 3, 6, 8,
       8, 8, 7, 7, 8, 4, 7, 6, 0, 4, 3, 7, 9, 5, 0, 3, 4, 4, 7, 7, 8, 1,
       7, 6, 4, 2, 3, 4, 0, 5, 1, 6, 5, 9, 3, 6, 3, 6, 1, 9, 9, 9, 5, 7,
       1, 7, 7, 7, 4, 5, 1, 7, 1, 7, 8, 9, 6, 7, 0, 5, 6, 1, 6, 5, 2, 8,
       4, 8, 7, 5, 4, 0, 6, 6, 1, 3, 5, 1, 2, 1, 3, 8, 8, 6, 8, 2, 3, 6,
       9, 3, 0, 4, 6, 5, 1, 7, 2, 6, 6, 7, 9, 6, 1, 9, 2, 4, 4, 4, 8, 1,
       4, 6, 0, 3, 3, 3, 5, 4, 5, 9, 6, 1, 3, 2, 0, 1, 5, 3, 1, 1, 3, 0,
       2, 2, 6, 8, 5, 4, 9, 7, 3, 2, 8, 0, 8, 2, 1, 9, 9, 4, 0, 4, 6, 7,
       9, 1, 4, 1, 1, 7, 4, 4, 5, 3, 1, 7, 7, 9, 6, 5, 0, 2, 2, 6, 8, 9,
       2, 1, 8, 3, 1, 9, 3, 9, 7, 4, 8, 1, 7, 7, 0, 3, 6, 8, 9, 0, 4, 4,
       4, 5, 2, 3, 4, 9, 4, 9, 5, 0, 5, 8, 6, 9, 9,

In [21]:
svm.score(x_test, y_test)

0.9916666666666667

In [22]:
rf = RandomForestClassifier(n_estimators=40)

In [23]:
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=40)

In [24]:
rf.predict(x_test)

array([9, 2, 5, 9, 2, 1, 5, 8, 1, 0, 5, 3, 5, 9, 7, 1, 2, 1, 8, 2, 3, 3,
       5, 1, 9, 6, 2, 7, 5, 2, 0, 1, 2, 7, 6, 7, 5, 7, 5, 4, 9, 7, 4, 6,
       9, 8, 5, 6, 8, 4, 9, 5, 5, 2, 7, 9, 8, 6, 8, 0, 9, 0, 1, 3, 6, 5,
       4, 2, 8, 6, 0, 2, 9, 1, 2, 3, 5, 6, 6, 2, 5, 1, 8, 7, 8, 3, 6, 8,
       8, 8, 4, 7, 8, 4, 7, 6, 0, 7, 3, 7, 9, 5, 0, 3, 4, 4, 7, 7, 8, 1,
       7, 6, 4, 2, 3, 4, 0, 5, 1, 6, 5, 9, 3, 5, 3, 6, 1, 9, 9, 9, 5, 7,
       1, 7, 7, 7, 4, 5, 1, 7, 1, 7, 8, 9, 6, 7, 0, 5, 6, 1, 6, 5, 2, 8,
       4, 8, 7, 5, 4, 0, 6, 6, 1, 3, 5, 1, 2, 1, 3, 8, 8, 1, 8, 2, 3, 6,
       9, 3, 0, 4, 6, 5, 1, 7, 2, 6, 6, 7, 9, 6, 1, 9, 2, 4, 4, 4, 7, 1,
       4, 6, 0, 3, 3, 3, 5, 4, 5, 9, 6, 1, 3, 2, 0, 1, 9, 3, 1, 1, 3, 0,
       2, 2, 6, 8, 5, 4, 9, 7, 3, 2, 8, 0, 8, 2, 1, 9, 9, 4, 0, 4, 6, 7,
       9, 1, 4, 8, 1, 7, 4, 4, 5, 7, 1, 7, 7, 9, 6, 5, 0, 2, 2, 6, 8, 9,
       2, 1, 8, 3, 1, 9, 3, 9, 7, 4, 8, 1, 7, 7, 0, 3, 6, 8, 9, 0, 4, 4,
       4, 5, 2, 3, 4, 9, 4, 9, 5, 0, 5, 8, 6, 9, 9,

In [25]:
rf.score(x_test, y_test)

0.9666666666666667

In [26]:
from sklearn.model_selection import KFold

In [27]:
kf = KFold(n_splits= 3)

In [28]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [29]:
for train_index, test_index in kf.split(digit.data):
    print(train_index, test_index)

[ 599  600  601 ... 1794 1795 1796] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

In [30]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
def Score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [32]:
Score(LogisticRegression(max_iter=2000), x_train, x_test, y_train, y_test)

0.9666666666666667

In [33]:
Score(SVC(), x_train, x_test, y_train, y_test)

0.9916666666666667

In [34]:
Score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test)

0.9611111111111111

In [35]:
from sklearn.model_selection import StratifiedKFold

In [36]:
skf = StratifiedKFold(n_splits=3)

In [37]:
for train_index, test_index in skf.split(digit.data, digit.target):
    print(train_index, test_index)

[ 588  590  591 ... 1794 1795 1796] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

In [38]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in skf.split(digit.data, digit.target):
    x_train, x_test, y_train, y_test = digit.data[train_index], digit.data[test_index], \
    digit.target[train_index], digit.target[test_index]

    print(Score(LogisticRegression(max_iter=2000), x_train, x_test, y_train, y_test))
    print(Score(SVC(), x_train, x_test, y_train, y_test))
    print(Score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))


0.9198664440734557


0.9649415692821369
0.9298831385642737
0.9415692821368948
0.9799666110183639
0.9499165275459098
0.9165275459098498
0.9649415692821369
0.9248747913188647


In [43]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in skf.split(digit.data, digit.target):
    x_train, x_test, y_train, y_test = digit.data[train_index], digit.data[test_index], \
    digit.target[train_index], digit.target[test_index]

    score_lr.append(Score(LogisticRegression(max_iter=2000), x_train, x_test, y_train, y_test))
    score_svm.append(Score(SVC(), x_train, x_test, y_train, y_test))
    score_rf.append(Score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))


In [40]:
score_lr

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [41]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [44]:
score_rf

[0.9215358931552587, 0.9549248747913188, 0.9315525876460768]

In [45]:
from sklearn.model_selection import cross_val_score

In [47]:
cross_val_score(LogisticRegression(max_iter= 2000), digit.data, digit.target)

array([0.92222222, 0.87222222, 0.94150418, 0.93871866, 0.89693593])

In [48]:
cross_val_score(SVC(), digit.data, digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [50]:
cross_val_score(RandomForestClassifier(n_estimators= 40), digit.data, digit.target)

array([0.93055556, 0.90555556, 0.95821727, 0.97493036, 0.91364903])

In [51]:
cross_val_score(RandomForestClassifier(n_estimators= 10), digit.data, digit.target)

array([0.91111111, 0.84444444, 0.93314763, 0.94428969, 0.88022284])

In [52]:
cross_val_score(RandomForestClassifier(n_estimators= 20), digit.data, digit.target)

array([0.92222222, 0.90833333, 0.95264624, 0.94428969, 0.9275766 ])

In [53]:
cross_val_score(RandomForestClassifier(n_estimators= 30), digit.data, digit.target)

array([0.94444444, 0.90833333, 0.95264624, 0.96100279, 0.90529248])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators= 50), digit.data, digit.target)

array([0.93055556, 0.91388889, 0.94986072, 0.97214485, 0.93314763])

In [55]:
cross_val_score(RandomForestClassifier(n_estimators= 60), digit.data, digit.target)

array([0.92777778, 0.90277778, 0.94986072, 0.95543175, 0.92200557])