In [392]:
import pandas as pd
import numpy as np

In [393]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor

In [394]:
import random

In [395]:
x,y = load_diabetes(return_X_y=True)

In [396]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [397]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [398]:
x.shape

(442, 10)

In [399]:
y.shape

(442,)

In [400]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [401]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [402]:
x_test

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

In [403]:
model = LinearRegression()

In [404]:
model.fit(x_train,y_train)

LinearRegression()

In [405]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [406]:
model.intercept_

151.88331005254167

In [407]:
prediction = model.predict(x_test)

In [408]:
r2_score(y_test,prediction)

0.4399338661568969

In [409]:
class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [410]:
mbr = MBGDRegressor(batch_size=int(x_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [411]:
mbr.fit(x_train,y_train)

149.27499069137045 [  33.45042218 -140.39247586  438.95254461  301.83890552  -20.66857832
  -88.56789367 -193.05248006  116.56349113  400.46077002  112.90327155]


In [412]:
y_pred = mbr.predict(x_test)

In [413]:
r2_score(y_test,y_pred)

0.45179961504994637

In [414]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [415]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [416]:
sgd.intercept_

array([176.35566087])

In [417]:
sgd.coef_

array([  58.95338642,  -78.24785884,  352.21105833,  232.57326172,
         12.19147523,  -43.28524845, -180.81575312,  116.58038253,
        332.65415034,  112.84080674])

In [418]:
y_pred = sgd.predict(x_test)

In [419]:
r2_score(y_test,y_pred)

0.3345939057029559