In [1]:
import pandas as pd
import numpy as np

In [17]:
from sklearn.datasets import make_regression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [56]:
import plotly.express as px
import plotly.graph_objects as go

In [87]:
x, y = make_regression(n_samples=100, n_features=2, n_targets=1, n_informative=2, noise=50)

In [88]:
df = pd.DataFrame({'feature1': x[:,0], 'feature2': x[:,1], 'target': y})

In [89]:
df

feature1  feature2      target
0   2.564751  1.421892  204.807509
1   0.520178  0.798050  132.344533
2  -1.999921  1.523097   28.338282
3   1.742663 -0.479780   73.508743
4  -0.669184 -0.063186  -49.850177
..       ...       ...         ...
95 -1.012832 -0.418728 -106.188682
96  1.689682  0.167482   74.618783
97  0.611942  0.194214  -39.117245
98  0.726655  1.464750   24.941878
99 -1.104043 -1.746333  -89.504212

[100 rows x 3 columns]

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   feature1  100 non-null    float64
 1   feature2  100 non-null    float64
 2   target    100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB


In [91]:
df.isnull().sum()

feature1    0
feature2    0
target      0
dtype: int64

In [92]:
df.describe()

feature1    feature2      target
count  100.000000  100.000000  100.000000
mean    -0.002002   -0.063507    0.419444
std      0.958778    0.957895   66.311698
min     -3.327183   -2.421281 -217.955581
25%     -0.522697   -0.618033  -38.823879
50%      0.015296   -0.038515    9.896967
75%      0.566396    0.575703   42.441185
max      2.564751    2.050284  204.807509

In [93]:
px.scatter_3d(df, x='feature1', y='feature2', z = 'target')

In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [95]:
model = LinearRegression()

In [96]:
model.fit(x_train, y_train)

LinearRegression()

In [97]:
prediction = model.predict(x_test)

In [98]:
mean_absolute_error(y_test, prediction)

38.90968011706813

In [99]:
mean_squared_error(y_test, prediction)

1960.4207452724756

In [100]:
r2_score(y_test, prediction)

-0.35151655552203476

In [104]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

In [105]:
x

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [106]:
y

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [118]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

z_final = model.predict(final).reshape(10,10)

z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [119]:
xGrid

array([[-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ],
       [-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
         0.55555556,  1.66666667,  2.77777778

In [120]:

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [110]:
z_final

array([[-359.15983818, -314.79483749, -270.4298368 , -226.0648361 ,
        -181.69983541, -137.33483472,  -92.96983403,  -48.60483334,
          -4.23983265,   40.12516804],
       [-323.27939899, -278.9143983 , -234.54939761, -190.18439692,
        -145.81939623, -101.45439554,  -57.08939485,  -12.72439416,
          31.64060653,   76.00560723],
       [-287.39895981, -243.03395912, -198.66895843, -154.30395774,
        -109.93895704,  -65.57395635,  -21.20895566,   23.15604503,
          67.52104572,  111.88604641],
       [-251.51852062, -207.15351993, -162.78851924, -118.42351855,
         -74.05851786,  -29.69351717,   14.67148352,   59.03648421,
         103.4014849 ,  147.76648559],
       [-215.63808144, -171.27308075, -126.90808006,  -82.54307937,
         -38.17807867,    6.18692202,   50.55192271,   94.9169234 ,
         139.28192409,  183.64692478],
       [-179.75764225, -135.39264156,  -91.02764087,  -46.66264018,
          -2.29763949,   42.0673612 ,   86.43236189,  130

In [112]:
z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [113]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

In [114]:
fig.add_trace(go.Surface(x = x, y = y, z =z ))

In [115]:
fig.show()

In [116]:

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [121]:
x = np.linspace(df['feature1'].min(), df['feature1'].max(), 10)
y = np.linspace(df['feature2'].min(), df['feature2'].max(), 10)

In [122]:
xGrid, yGrid = np.meshgrid(x, y)

In [123]:
final = np.c_[xGrid.ravel(), yGrid.ravel()]
z_final = model.predict(final).reshape(xGrid.shape)

In [133]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target', width=1000, height=1000)

In [134]:
fig.add_trace(go.Surface(x=xGrid, y=yGrid, z=z_final, opacity=0.6))

In [136]:
fig.show()