In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('titanic_data.csv')

In [3]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [9]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis= 'columns', inplace= True)

In [10]:
df

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [11]:
inputs = df.drop('Survived', axis = 'columns')
target = df.Survived

In [12]:
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [13]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [16]:
dummies = pd.get_dummies(inputs.Sex)
dummies

female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [18]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs

Pclass     Sex   Age     Fare  female   male
0         3    male  22.0   7.2500   False   True
1         1  female  38.0  71.2833    True  False
2         3  female  26.0   7.9250    True  False
3         1  female  35.0  53.1000    True  False
4         3    male  35.0   8.0500   False   True
..      ...     ...   ...      ...     ...    ...
886       2    male  27.0  13.0000   False   True
887       1  female  19.0  30.0000    True  False
888       3  female   NaN  23.4500    True  False
889       1    male  26.0  30.0000   False   True
890       3    male  32.0   7.7500   False   True

[891 rows x 6 columns]

In [19]:
inputs.drop('Sex', axis = 'columns', inplace= True)
inputs

Pclass   Age     Fare  female   male
0         3  22.0   7.2500   False   True
1         1  38.0  71.2833    True  False
2         3  26.0   7.9250    True  False
3         1  35.0  53.1000    True  False
4         3  35.0   8.0500   False   True
..      ...   ...      ...     ...    ...
886       2  27.0  13.0000   False   True
887       1  19.0  30.0000    True  False
888       3   NaN  23.4500    True  False
889       1  26.0  30.0000   False   True
890       3  32.0   7.7500   False   True

[891 rows x 5 columns]

In [20]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [23]:
inputs['Age'] = inputs.Age.fillna(inputs.Age.mean())
inputs

Pclass        Age     Fare  female   male
0         3  22.000000   7.2500   False   True
1         1  38.000000  71.2833    True  False
2         3  26.000000   7.9250    True  False
3         1  35.000000  53.1000    True  False
4         3  35.000000   8.0500   False   True
..      ...        ...      ...     ...    ...
886       2  27.000000  13.0000   False   True
887       1  19.000000  30.0000    True  False
888       3  29.699118  23.4500    True  False
889       1  26.000000  30.0000   False   True
890       3  32.000000   7.7500   False   True

[891 rows x 5 columns]

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [45]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [46]:
model.fit(x_train, y_train)

GaussianNB()

In [47]:
model.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0], dtype=int64)

In [48]:
model.score(x_test, y_test)

0.7821229050279329

In [38]:
df

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

In [39]:
inputs

Pclass        Age     Fare  female   male
0         3  22.000000   7.2500   False   True
1         1  38.000000  71.2833    True  False
2         3  26.000000   7.9250    True  False
3         1  35.000000  53.1000    True  False
4         3  35.000000   8.0500   False   True
..      ...        ...      ...     ...    ...
886       2  27.000000  13.0000   False   True
887       1  19.000000  30.0000    True  False
888       3  29.699118  23.4500    True  False
889       1  26.000000  30.0000   False   True
890       3  32.000000   7.7500   False   True

[891 rows x 5 columns]

In [49]:
y_test[:10]

718    0
197    0
491    0
790    0
99     0
124    0
867    0
92     0
464    0
154    0
Name: Survived, dtype: int64

In [50]:
model.predict(x_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [51]:
model.predict_proba(x_test)

array([[9.89697378e-01, 1.03026224e-02],
       [9.89896615e-01, 1.01033853e-02],
       [9.87789837e-01, 1.22101625e-02],
       [9.89493471e-01, 1.05065294e-02],
       [9.76865653e-01, 2.31343469e-02],
       [6.42501356e-01, 3.57498644e-01],
       [8.67220141e-01, 1.32779859e-01],
       [8.15001473e-01, 1.84998527e-01],
       [9.89511538e-01, 1.04884622e-02],
       [9.89465604e-01, 1.05343962e-02],
       [3.22688227e-03, 9.96773118e-01],
       [9.76520420e-01, 2.34795796e-02],
       [9.74851726e-01, 2.51482738e-02],
       [3.86137430e-02, 9.61386257e-01],
       [5.14090729e-02, 9.48590927e-01],
       [5.21002143e-02, 9.47899786e-01],
       [9.76539962e-01, 2.34600378e-02],
       [9.87146439e-01, 1.28535609e-02],
       [5.23249256e-02, 9.47675074e-01],
       [9.80540715e-01, 1.94592849e-02],
       [4.82114998e-02, 9.51788500e-01],
       [2.82244256e-02, 9.71775574e-01],
       [9.78095660e-01, 2.19043396e-02],
       [1.76043549e-03, 9.98239565e-01],
       [2.385669