In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('customer.csv')
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [10]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [12]:
df.describe()

age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [14]:
df2 = df.iloc[:,2:]

In [16]:
df2.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, t_test = train_test_split(df2.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [19]:
x_train.head()

review education
45   Poor        PG
12   Poor    School
10   Good        UG
11   Good        UG
19   Poor        PG

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'], ['School','UG','PG']])

In [22]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [25]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

C:\Users\shoab\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [26]:
x_train

array([[0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.]])

In [27]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [36]:
le.fit(y_train)


LabelEncoder()

In [38]:
le.classes_

array([0, 1])

In [40]:
y_train = le.transform(y_train)


In [41]:
y_train

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0], dtype=int64)