In [205]:
import pandas as pd
import numpy as np

In [206]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge


from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score

In [207]:
x,y = load_diabetes(return_X_y=True)

In [208]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [209]:
x_train

array([[ 0.07076875,  0.05068012,  0.01211685, ...,  0.03430886,
         0.02736405, -0.0010777 ],
       [-0.00914709,  0.05068012, -0.01806189, ...,  0.07120998,
         0.00027248,  0.01963284],
       [ 0.00538306, -0.04464164,  0.04984027, ..., -0.00259226,
         0.01703607, -0.01350402],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]])

In [210]:
x_test

array([[ 0.04534098, -0.04464164, -0.00620595, -0.01599898,  0.1250187 ,
         0.1251981 ,  0.019187  ,  0.03430886,  0.03243232, -0.0052198 ],
       [ 0.09256398, -0.04464164,  0.03690653,  0.02187239, -0.02496016,
        -0.01665815,  0.00077881, -0.03949338, -0.02251653, -0.02178823],
       [ 0.06350368,  0.05068012, -0.00405033, -0.01255612,  0.10300346,
         0.04878988,  0.05600338, -0.00259226,  0.08449153, -0.01764613],
       [ 0.09619652, -0.04464164,  0.0519959 ,  0.07926471,  0.05484511,
         0.03657709, -0.07653559,  0.14132211,  0.09864806,  0.06105391],
       [ 0.01264814,  0.05068012, -0.02021751, -0.00222757,  0.03833367,
         0.05317395, -0.00658447,  0.03430886, -0.00514219, -0.00936191],
       [ 0.0090156 , -0.04464164, -0.02452876, -0.02632753,  0.0988756 ,
         0.0941964 ,  0.07072993, -0.00259226, -0.02139531,  0.00720652],
       [-0.00914709,  0.05068012,  0.17055523,  0.01498668,  0.03007796,
         0.03375875, -0.02131102,  0.03430886

In [211]:
model = Ridge(alpha=0.1)

In [212]:
model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [213]:
prediction = model.predict(x_test)


In [214]:
r2_score(y_test, prediction)

0.46085219464119254

In [215]:
model2 = Ridge(alpha=0.1, solver='cholesky')

In [216]:
model2.fit(x_train,y_train)

Ridge(alpha=0.1, solver='cholesky')

In [217]:
prediction = model.predict(x_test)

In [218]:
r2_score(y_test, prediction)

0.46085219464119254

In [219]:
model2.coef_

array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
       -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
        392.28931896,   79.9081772 ])

In [220]:
model2.intercept_

151.4585745667961

In [221]:
class ridge_test:
    
    def __init__(self,alpha=0.1):
        
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,x_train,y_train):
        
        x_train = np.insert(x_train,0,1,axis=1)
        I = np.identity(x_train.shape[1])
        I[0][0] = 0
        result = np.linalg.inv(np.dot(x_train.T,x_train) + self.alpha * I).dot(x_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]
    
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [222]:
model3 = ridge_test()

In [223]:
model3.fit(x_train, y_train)

In [224]:
prediction2 = model3.predict(x_test)

In [225]:
r2_score(y_test, prediction2)

0.46085219464119254

In [226]:
model3.intercept_

151.45857456679613

In [227]:
model3.coef_

array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
       -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
        392.28931896,   79.9081772 ])